/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SubsitutionPanel.java
 *
 * Created on 17-mei-2011, 16:34:54
 */
package equa.factbreakdown.gui;

/**
 *
 * @author FrankP
 */
public class SubstitutionMatchPanel extends MatchPanel {

    private static final long serialVersionUID = 1L;
    private String originalRoleName;
    private MatchPanel next;
    private int roleNumber;
    private boolean moved;

    /**
     * Creates new form SubsitutionPanel
     */
    public SubstitutionMatchPanel(int nr, String roleName, String typeName) {
        initComponents();
        moved = false;
        this.roleNumber = nr;
        originalRoleName = roleName;
        next = null;
        tfRoleName.setText(roleName);

        tfRoleName.setColumns(roleName.length());
        tfTypeName.setText(typeName);
        tfTypeName.setColumns(typeName.length());
    }

    @Override
    public String getText() {
        return tfValue.getText().trim();
    }

    @Override
    public void setNext(MatchPanel panel) {
        next = panel;
    }

    @Override
    public MatchPanel getNext() {
        return next;
    }

    public String getRoleName() {
        return tfRoleName.getText().trim();
    }

    public boolean isRoleNameChanged() {
        return !originalRoleName.equals(tfRoleName.getText());
    }

    public int getRoleNumber() {
        return roleNumber;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSubstitution = new javax.swing.JPanel();
        tfValue = new javax.swing.JTextField();
        pnDefinedRole = new javax.swing.JPanel();
        tfRoleName = new javax.swing.JTextField();
        tfTypeName = new javax.swing.JTextField();
        pnSwap = new javax.swing.JPanel();
        btSwap = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        pnSubstitution.setName("pnSubstitution"); // NOI18N
        pnSubstitution.setLayout(new java.awt.GridLayout(0, 1));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(SubstitutionMatchPanel.class);
        tfValue.setFont(resourceMap.getFont("value.font")); // NOI18N
        tfValue.setText(resourceMap.getString("value.text")); // NOI18N
        tfValue.setToolTipText(resourceMap.getString("value.toolTipText")); // NOI18N
        tfValue.setName("value"); // NOI18N
        tfValue.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
			public void mouseDragged(java.awt.event.MouseEvent evt) {
                tfValueMouseDragged(evt);
            }
        });
        tfValue.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValueActionPerformed(evt);
            }
        });
        pnSubstitution.add(tfValue);

        pnDefinedRole.setName("pnDefinedRole"); // NOI18N

        tfRoleName.setText(resourceMap.getString("tfRoleName.text")); // NOI18N
        tfRoleName.setToolTipText(resourceMap.getString("tfRoleName.toolTipText")); // NOI18N
        tfRoleName.setMinimumSize(new java.awt.Dimension(20, 20));
        tfRoleName.setName("tfRoleName"); // NOI18N
        tfRoleName.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfRoleNameMouseClicked(evt);
            }
        });
        pnDefinedRole.add(tfRoleName);

        tfTypeName.setEditable(false);
        tfTypeName.setForeground(resourceMap.getColor("tfTypeName.foreground")); // NOI18N
        tfTypeName.setText(resourceMap.getString("tfTypeName.text")); // NOI18N
        tfTypeName.setName("tfTypeName"); // NOI18N
        pnDefinedRole.add(tfTypeName);

        pnSubstitution.add(pnDefinedRole);

        add(pnSubstitution, java.awt.BorderLayout.CENTER);

        pnSwap.setMinimumSize(new java.awt.Dimension(10, 40));
        pnSwap.setName("pnSwap"); // NOI18N
        pnSwap.setLayout(new java.awt.BorderLayout());

        btSwap.setFont(resourceMap.getFont("btSwap.font")); // NOI18N
        btSwap.setText(resourceMap.getString("btSwap.text")); // NOI18N
        btSwap.setName("btSwap"); // NOI18N
        btSwap.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSwapActionPerformed(evt);
            }
        });
        pnSwap.add(btSwap, java.awt.BorderLayout.CENTER);

        add(pnSwap, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    private void tfValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValueActionPerformed
        moveText();
    }

    private void moveText() {
        if (moved) {
            return;
        }

        moved = true;

        int caretPosition = tfValue.getCaretPosition();
        String value = tfValue.getText();
        while (caretPosition > 0 && Character.isWhitespace(value.charAt(caretPosition - 1))) {
            caretPosition--;
        }
        String toMove = value.substring(caretPosition);
        tfValue.setText(value.substring(0, caretPosition));
        next.appendFront(toMove);
        refreshLayout();
    }//GEN-LAST:event_tfValueActionPerformed

    private void tfValueMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfValueMouseDragged
        if (!moved && tfValue.getCaretPosition() >= tfValue.getSelectionStart()
                && tfValue.getSelectionStart() > 0) {
            moveText();
        }
    }//GEN-LAST:event_tfValueMouseDragged

    private void btSwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSwapActionPerformed
        if (next.getNext() == null) {
            return;
        }
        SubstitutionMatchPanel right = (SubstitutionMatchPanel) next.getNext();
        int roleNumberCopy = roleNumber;
        String roleNameCopy = tfRoleName.getText();
        String typeNameCopy = tfTypeName.getText();

        roleNumber = right.roleNumber;
        tfRoleName.setText(right.tfRoleName.getText());
        tfTypeName.setText(right.tfTypeName.getText());

        right.roleNumber = roleNumberCopy;
        right.tfRoleName.setText(roleNameCopy);
        right.tfTypeName.setText(typeNameCopy);

        System.out.println("Switch between role " + right.roleNumber + " and "
                + roleNumber + ".");
        refreshLayout();

    }//GEN-LAST:event_btSwapActionPerformed

    private void tfRoleNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfRoleNameMouseClicked
        if (tfRoleName.getText().isEmpty()) {
            tfRoleName.setColumns(6);
            refreshLayout();
        }
    }//GEN-LAST:event_tfRoleNameMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSwap;
    private javax.swing.JPanel pnDefinedRole;
    private javax.swing.JPanel pnSubstitution;
    private javax.swing.JPanel pnSwap;
    private javax.swing.JTextField tfRoleName;
    private javax.swing.JTextField tfTypeName;
    private javax.swing.JTextField tfValue;
    // End of variables declaration//GEN-END:variables

    @Override
    public void appendFront(String toMove) {
        tfValue.setText(toMove + tfValue.getText());
    }

    public void setText(String expression) {
        tfValue.setText(expression);
    }
}
